"""Reviewed answers (the FAQ store), unanswered questions, and the console's
drafting tools that write into them.

Moved out of main.py verbatim (2026-09-25). Registered on the app through
app.include_router; paths, parameters and responses are unchanged.
"""

import logging
import os
import re

from fastapi import APIRouter, File, Header, HTTPException, Request, UploadFile
from pydantic import BaseModel

import faq_store
from guards import _require_admin
from providers import _available_providers, _default_model_for

logger = logging.getLogger(__name__)
router = APIRouter()


# ── FAQ (v10.4) — doc2query questions per product, admin-editable ─────

@router.get("/faq")
def faq_list(product: str | None = None):
    """Generated questions for a product (or all). Public read.

    Deliberately UNFILTERED: this is what the admin console lists, and an
    entry too ugly to show a visitor is exactly the one an admin needs to
    find and rewrite. Each carries a `displayable` flag so the console can
    surface them for curation -- the guest-facing list at /widget/faq is the
    one that hides them.
    """
    return {"faq": [dict(f, displayable=faq_store.is_displayable(f))
                    for f in faq_store.list_for_product(product)]}


class FaqGenerateReq(BaseModel):
    source: str
    product: str = ""
    category: str = ""
    questions: list[dict]  # [{question, answer?}]


@router.post("/faq/generate")
def faq_generate(payload: FaqGenerateReq, x_admin_password: str | None = Header(default=None)):
    """v10.13: store FAQ questions GENERATED BY THE FRONTEND. The browser
    calls the LLM API directly (using the key it already holds for Online
    chat), so the backend needs NO API key. It just persists what the
    admin generated."""
    _require_admin(x_admin_password)
    qa = [{"question": q.get("question", "").strip(),
           "answer": q.get("answer", "")}
          for q in payload.questions if q.get("question", "").strip()]
    if not qa:
        raise HTTPException(status_code=400, detail="No questions provided")

    # v12.0: MERGE by default. record_questions() replaces every entry for
    # a source, so regenerating destroyed manually-added questions and reset
    # curated answers. merge_questions() adds only questions not already
    # present in the same product scope (compared case- and punctuation-
    # insensitively) and never overwrites an existing entry, which makes
    # "Generate" safe to press repeatedly.
    if getattr(payload, "replace", False):
        faq_store.record_questions(payload.source, payload.product, qa,
                                   category=payload.category)
        return {"stored": len(qa), "replaced": True, "source": payload.source}

    result = faq_store.merge_questions(payload.source, payload.product, qa,
                                       category=payload.category)
    return {**result, "replaced": False, "source": payload.source}


class FaqEdit(BaseModel):
    # v12.0: the QUESTION is editable too. Previously only the answer could
    # be changed, so a badly-worded generated question could only be deleted
    # and retyped.
    question: str | None = None
    answer: str | None = None
    # Which products this answer applies to, comma-joined. None leaves the
    # tagging alone; "" means it applies to every product, which is what an
    # untagged answer has always meant.
    products: str | None = None


class FaqCreate(BaseModel):
    question: str
    answer: str = ""
    product: str = ""
    category: str = ""


@router.post("/faq")
def faq_create(payload: FaqCreate, x_admin_password: str | None = Header(default=None)):
    """Add a FAQ question by hand (v12.0). Stored with origin="manual" and
    edited=True so a later Generate can neither overwrite nor duplicate it."""
    _require_admin(x_admin_password)
    try:
        entry = faq_store.add_entry(payload.question, payload.answer,
                                    products=payload.product,
                                    category=payload.category)
    except ValueError as e:
        # 409 so the UI can show "that question already exists".
        raise HTTPException(status_code=409, detail=str(e))
    # A hand-written answer may be closing a question that's sitting in the
    # gaps backlog — auto-resolve it rather than making the admin do it twice.
    faq_store.resolve_gap_matching(payload.question, faq_id=entry.get("id"))
    return entry


@router.patch("/faq/{faq_id}")
def faq_edit(faq_id: str, payload: FaqEdit, x_admin_password: str | None = Header(default=None)):
    _require_admin(x_admin_password)
    updated = faq_store.update_entry(faq_id, payload.question, payload.answer,
                                     products=payload.products)
    if not updated:
        raise HTTPException(status_code=404, detail="FAQ entry not found")
    return updated


@router.delete("/faq")
def faq_delete_all(product: str | None = None,
                   source: str | None = None,
                   confirm: bool = False,
                   x_admin_password: str | None = Header(default=None)):
    """Bulk-delete FAQ entries (v12.0).

    Requires ?confirm=true — a second lock behind the UI's warning dialog.
    With no scope this wipes the entire curated FAQ, which is hand-written
    content with no undo.
    """
    _require_admin(x_admin_password)
    if not confirm:
        raise HTTPException(status_code=400,
                            detail="Refusing bulk delete without confirm=true")
    removed = faq_store.delete_all(scope_key=product, source=source)
    return {"deleted": removed, "scope": product or source or "ALL"}


def _category_product_keys(key: str) -> set[str]:
    """Product keys inside the category `key`, or an empty set if `key` is
    not a category. Used to make a range selection mean "everything in this
    range" rather than "the handful of questions filed against the range
    itself"."""
    try:
        import catalog as _cat
        for c in _cat.catalog().get("categories", []):
            if c.get("key") == key:
                return {p.get("key") for p in c.get("products", []) if p.get("key")}
    except Exception as exc:
        logger.warning(f"category expansion failed for {key!r}: {exc}")
    return set()


@router.get("/faq/gaps")
def faq_gaps(product: str | None = None,
             sort: str = "demand",
             group_similar: bool = True,
             x_admin_password: str | None = Header(default=None)):
    """Questions the FAQ could not answer — either nothing was close enough
    to suggest, or the user rejected the suggestions (v12.0). This is the
    FAQ backlog, prioritised by real demand rather than guesswork.

    `group_similar` folds rewordings of the same question into one entry
    (faq_store.cluster_gaps) so `times_asked` reflects how many people
    actually asked a thing, not how many distinct phrasings they used. Six
    ways of asking "what is the nv9 pinout" is one backlog item, not six.
    Grouping happens at read time and never rewrites the stored gaps, so
    turning it off returns the raw list unchanged.

    `sort` is what the console's control drives:
        demand  - most-asked first (the default; this is a work queue)
        latest  - most recently asked first, for "what is happening now"
        product - grouped by scope, then by demand within each
    """
    _require_admin(x_admin_password)
    # "__none__" is the console's way of asking for questions recorded with
    # no product at all. list_gaps' scope_key filter cannot express that
    # (an empty string means "no filter"), so it is handled here.
    if product == "__none__":
        gaps = [g for g in faq_store.list_gaps(None) if not g.get("scope")]
    elif product and _category_product_keys(product):
        # A CATEGORY, not a product. Gaps are filed against product keys, so
        # filtering on the category key alone matched nothing and the console
        # showed "0 entries" for a range that plainly had questions in it.
        # Expand it to the products it contains, and keep the category key
        # itself: a question asked with only a range selected is filed under
        # that key and belongs in this view too.
        wanted = _category_product_keys(product) | {product}
        gaps = [g for g in faq_store.list_gaps(None)
                if (g.get("scope") or "") in wanted]
    else:
        gaps = faq_store.list_gaps(product)

    if group_similar:
        gaps = faq_store.cluster_gaps(gaps)

    if sort == "latest":
        gaps = sorted(gaps, key=lambda g: -(g.get("ts") or 0))
    elif sort == "product":
        gaps = sorted(gaps, key=lambda g: ((g.get("scope") or "\uffff"),
                                           -int(g.get("times_asked", 1))))
    # "demand" is the order list_gaps/cluster_gaps already return.

    # One pass over the unfiltered set feeds both the scope list and the
    # per-scope totals below.
    _scope_totals: dict[str, dict] = {}
    for _g in faq_store.list_gaps(None):
        _e = _scope_totals.setdefault(_g.get("scope") or "",
                                      {"questions": 0, "asks": 0})
        _e["questions"] += 1
        _e["asks"] += int(_g.get("times_asked") or 1)

    return {
        "gaps": gaps,
        "stats": faq_store.gap_stats(),
        # What the filter control offers, derived from the gaps themselves
        # rather than the catalogue: a scope that no longer exists as a
        # product (nv9st, coin_hoppers) still has real questions filed under
        # it, and hiding it from the filter would hide those questions.
        "scopes": sorted(_scope_totals),
        # How much each product is carrying, so the console can show it on
        # the filter itself rather than making someone select a product to
        # find out whether it has anything in it. Counted over ALL gaps, not
        # the filtered view, or every count would collapse to the one
        # product currently selected.
        "scope_counts": _scope_totals,
        "grouped": bool(group_similar),
        "sort": sort,
    }


@router.delete("/faq/gaps/{gap_id}")
def faq_gap_dismiss(gap_id: str, x_admin_password: str | None = Header(default=None)):
    """Dismiss a gap outright — for spam and noise, which a public widget
    will accumulate, or a question addressed some other way."""
    _require_admin(x_admin_password)
    if not faq_store.dismiss_gap(gap_id):
        raise HTTPException(status_code=404, detail="Gap not found")
    return {"deleted": True}


class GapIds(BaseModel):
    ids: list[str]


@router.delete("/faq/gaps")
def faq_gaps_dismiss_bulk(payload: GapIds, x_admin_password: str | None = Header(default=None)):
    """Bulk dismiss_gap — the console's "Dismiss selected"."""
    _require_admin(x_admin_password)
    n = faq_store.dismiss_gap_bulk(payload.ids)
    return {"deleted": n}


@router.post("/faq/gaps/spam")
def faq_gaps_mark_spam(payload: GapIds, x_admin_password: str | None = Header(default=None)):
    """Flag gaps as spam (kept, never resurfaces) rather than deleting —
    see faq_store.mark_spam for why this is distinct from dismiss."""
    _require_admin(x_admin_password)
    n = faq_store.mark_spam_bulk(payload.ids)
    return {"marked": n}


class AnswerGapReq(BaseModel):
    gap_id: str
    provider: str | None = None
    model: str | None = None


@router.post("/admin/faq/answer_gap")
async def admin_answer_gap(payload: AnswerGapReq, x_admin_password: str | None = Header(default=None)):
    """Draft an answer for one unanswered gap using the same retrieval +
    generation pipeline /query already runs — NOT auto-saved to the FAQ.

    Every other generation path in this app (autogenerate, the old
    doc2query features) treats model output as reviewable-before-publish,
    never auto-published straight to visitors; this stays consistent with
    that rather than silently publishing an unverified answer. The admin
    reviews/edits the draft in the normal "Write one yourself" form.
    """
    _require_admin(x_admin_password)
    gaps = faq_store.list_gaps(include_resolved=True, include_spam=True)
    gap = next((g for g in gaps if g.get("id") == payload.gap_id), None)
    if not gap:
        raise HTTPException(status_code=404, detail="Gap not found")

    # The pipeline lives in main; imported at call time because main imports
    # this module while it is still being built.
    from main import QueryRequest, query
    req = QueryRequest(q=gap["question"], product=gap.get("scope"), skip_faq=True)
    if payload.provider:
        req.force_provider = payload.provider
        req.force_model = payload.model or _default_model_for(payload.provider)

    # query() is sync — run in the threadpool so this doesn't block the
    # event loop, same reasoning as _widget_answer below.
    from starlette.concurrency import run_in_threadpool
    result = run_in_threadpool(query, req, None)
    result = await result
    return {
        "question": gap["question"],
        "answer": result.get("answer", ""),
        "scope": gap.get("scope"),
        "sources": result.get("sources", []),
        "role": result.get("role"),
        "flagged": result.get("flagged", False),
        "model": result.get("model"),
        "provider": result.get("provider"),
    }


@router.delete("/faq/{faq_id}")
def faq_delete(faq_id: str, x_admin_password: str | None = Header(default=None)):
    _require_admin(x_admin_password)
    if not faq_store.delete_entry(faq_id):
        raise HTTPException(status_code=404, detail="FAQ entry not found")
    return {"deleted": True}


class FaqAutoReq(BaseModel):
    source: str
    product: str = ""
    category: str = ""
    count: int = 8
    # Admin-chosen override (console's model picker). Blank/omitted keeps
    # the existing default chain (generate_with_fallback("accurate", ...)).
    provider: str | None = None
    model: str | None = None


def _parse_qa_json(raw: str) -> list[dict]:
    """Extract [{question, answer}] from a model response.

    Small local models wrap JSON in prose or markdown fences routinely, so
    the array is located within the response rather than the whole response
    being handed to json.loads. Malformed output returns [] and the caller
    reports the failure — it is never partially stored.
    """
    import json as _json
    text = (raw or "").strip()
    text = re.sub(r"^```(?:json)?|```$", "", text, flags=re.MULTILINE).strip()
    start, end = text.find("["), text.rfind("]")
    if start == -1 or end == -1 or end <= start:
        return []
    try:
        data = _json.loads(text[start:end + 1])
    except Exception:
        return []
    if not isinstance(data, list):
        return []
    out = []
    for item in data:
        if not isinstance(item, dict):
            continue
        q = (item.get("question") or "").strip()
        a = (item.get("answer") or "").strip()
        if q:
            out.append({"question": q, "answer": a})
    return out


@router.post("/admin/faq/autogenerate")
def admin_faq_autogenerate(payload: FaqAutoReq,
                           x_admin_password: str | None = Header(default=None)):
    """Generate FAQ question/answer pairs from a document, SERVER-SIDE.

    /faq/generate expects the browser to have called an LLM itself and to
    post the results, which is why the old admin UI needed an API key in
    the browser. This does the generation here using the server's
    configured provider, so no key ever reaches a browser, and merges the
    result (existing questions and curated answers are never overwritten).
    """
    _require_admin(x_admin_password)

    sample = _draft_sample(payload.source)

    n = max(1, min(int(payload.count or 8), 20))
    prompt = _faq_prompt(sample, n)

    try:
        if payload.provider:
            from llm import generate
            model = payload.model or _default_model_for(payload.provider)
            out = generate(payload.provider, prompt, model)
            if not out or not out.get("text"):
                raise HTTPException(status_code=502,
                    detail=f"{payload.provider}/{model} returned nothing — "
                           f"check the key is set and the model name is correct.")
        else:
            from llm import generate_with_fallback
            out = generate_with_fallback("accurate", prompt)
    except HTTPException:
        raise
    except Exception as e:
        logger.warning(f"FAQ autogeneration call failed: {e}")
        raise HTTPException(status_code=502, detail=f"Drafting failed: {e}")

    raw = (out or {}).get("text", "") or ""

    # generate_with_fallback returns provider "none" when EVERY provider in the
    # chain failed -- a rejected key, an Ollama that is not running. Its
    # placeholder text ("I was unable to generate a response.") of course does
    # not parse, and the parse failure below then reported it as "the model did
    # not return usable pairs, try again" -- advice for a situation that cannot
    # succeed no matter how many times it is retried. Name the actual fault.
    if (out or {}).get("provider") == "none":
        raise HTTPException(
            status_code=502,
            detail="No model could be reached, so nothing was generated. Every "
                   "configured provider failed: check the provider API key in "
                   "src/.env is still valid, or start Ollama to draft locally.")

    pairs = _parse_qa_json(raw)
    if not pairs:
        # Logged because the endpoint used to discard the response entirely,
        # which made a parse failure impossible to diagnose from the server.
        logger.warning(
            "FAQ autogeneration parsed 0 pairs from %s/%s; raw head: %r",
            (out or {}).get("provider"), (out or {}).get("model"), raw[:300])
        # A local model that returns unparseable text is a normal, common
        # outcome, not an exception — say so plainly rather than storing
        # garbage or reporting a false success.
        raise HTTPException(
            status_code=422,
            detail="The model did not return usable question/answer pairs. "
                   "Try again, or switch to Online mode for drafting.")

    # Every table and checklist in the document goes in as a VERBATIM entry
    # alongside the drafted ones. These are the answers worth having in the
    # FAQ most: served from the store they are exact, instant, cost no
    # tokens, and cannot be paraphrased wrongly, refused by the grounding
    # gate, or hallucinated -- the answer IS the document's own table.
    verbatim = _verbatim_faq_pairs(payload.source)

    merged = faq_store.merge_questions(payload.source,
                                       payload.product or payload.category,
                                       verbatim + pairs[:n],
                                       category=payload.category)
    merged["source"] = payload.source
    merged["model"] = (out or {}).get("model")
    merged["verbatim_added"] = len(verbatim)
    return merged


def _verbatim_faq_pairs(source: str) -> list[dict]:
    """Tables and checklists from one document, as FAQ pairs. [] on any
    problem -- a document we cannot re-read should not fail FAQ drafting."""
    try:
        import docstore
        import structures
        # docstore.find, NOT os.path.join(store_dir(), source). `source`
        # arrives from a request body, and join() treats an absolute path
        # or a "../" prefix as an instruction rather than a filename -- so
        # this handed any readable file on the host to pdfplumber and put
        # whatever it could parse into drafted FAQ text. CodeQL reported it
        # as py/path-injection (alert 123) along with the four sinks in
        # structures.py it flows into.
        #
        # find() was written for exactly this and already satisfies the
        # analyser: it reduces the name to a bare basename (handling the
        # Windows-backslash case that basename() alone misses on POSIX),
        # then returns a path built from a matching os.listdir ENTRY, so no
        # caller-supplied text ever reaches the filesystem. It also covers
        # the legacy store directory, which the join did not -- a document
        # retained before v15 was previously invisible here.
        path = docstore.find(source)
        if not path:
            return []
        return [{"question": p["question"], "answer": p["answer"]}
                for p in structures.faq_pairs_for_document(path, source)]
    except Exception as exc:
        logger.warning(f"verbatim FAQ pairs skipped for {source}: {exc}")
        return []


def _faq_prompt(sample: str, n: int) -> str:
    """The drafting prompt, shared by the saving endpoint and the streaming
    one so the two cannot drift into producing different FAQs."""
    return (
        "You write support FAQ entries from product documentation.\n\n"
        f"<document>\n{sample}\n</document>\n\n"
        f"Write {n} question-and-answer pairs a customer might ask that this "
        "document answers. Rules:\n"
        "- Use ONLY facts stated in the document. Invent nothing.\n"
        "- Each answer must read correctly on its own, without the question — "
        "write \"No internet connection is required\", not \"No\".\n"
        "- Keep answers to one or two sentences.\n"
        "- Skip anything the document does not actually state.\n\n"
        "Return ONLY a JSON array, no other text, in this exact form:\n"
        '[{"question": "...", "answer": "..."}]'
    )


def _draft_sample(source: str) -> str:
    from docindex import source_text
    sample, _ = source_text(source, max_chunks=12, cap=8000)
    if not sample.strip():
        raise HTTPException(
            status_code=404,
            detail=f"No indexed text found for '{source}'. If it was just "
                   f"uploaded, wait for processing to finish.")
    return sample


class FaqBulkReq(BaseModel):
    source: str = ""
    product: str = ""
    category: str = ""
    entries: list = []


@router.post("/admin/faq/draft/stream")
def admin_faq_draft_stream(payload: FaqAutoReq,
                           x_admin_password: str | None = Header(default=None)):
    """Draft FAQs and stream them as they are written. NOTHING IS SAVED.

    Two things this buys that the saving endpoint cannot. The wait stops
    being blank -- drafting eight pairs from a long manual is tens of
    seconds during which the old endpoint returned nothing at all, so the
    console could only show a spinner and hope. And the person reviewing
    sees the answers arrive in the order the model commits to them, which is
    the same order they will read them in.

    Saving is a separate, deliberate step (/admin/faq/bulk) because these
    are drafts: the console shows them for approval first, and anything
    dismissed there should never have touched the store.
    """
    _require_admin(x_admin_password)
    sample = _draft_sample(payload.source)
    n = max(1, min(int(payload.count or 8), 20))
    prompt = _faq_prompt(sample, n)
    provider, model = payload.provider, payload.model

    def events():
        import json as _json
        raw = []

        def sse(obj):
            return "data: " + _json.dumps(obj) + "\n\n"

        # The model stream starts FIRST. Extracting the document's tables
        # re-opens the PDF and walks every page, which on a long manual is the
        # pause before anything appears -- the reader waited through it with an
        # empty panel and then got everything at once. The tables follow the
        # drafting, by which point they are the fast half.
        verbatim = []
        try:
            from llm import stream_generate
            # No provider chosen means "whatever the server has": the picker
            # offers the same list, and an empty one is a real state on a
            # install with no key set.
            use = provider
            if not use:
                avail = _available_providers()
                if not avail:
                    yield sse({"type": "error", "message":
                               "No provider is configured, so nothing can be "
                               "drafted. Set an API key under API keys."})
                    return
                use = avail[0]["key"]
            mdl = model or _default_model_for(use)
            # stream_generate yields (delta, done) and stops silently on a
            # provider error, so an empty result is treated as a failure
            # below rather than as a finished draft.
            for delta, _done in stream_generate(use, prompt, mdl):
                if not delta:
                    continue
                raw.append(delta)
                yield sse({"type": "delta", "text": delta})
        except Exception as exc:
            # The DETAIL goes to the log, not down the wire. It used to be
            # `str(exc)[:200]`, which hands whatever the exception carries
            # to whoever is on the other end of the stream -- a provider
            # URL, a key fragment, a filesystem path, a driver stack. The
            # operator loses nothing: the same text is one line above, with
            # a request id around it, in a place only the operator reads.
            logger.warning(f"FAQ draft stream failed: {exc}", exc_info=True)
            yield sse({"type": "error", "message":
                       "The draft could not be generated. Please try again."})
            return

        pairs = _parse_qa_json("".join(raw))
        if not pairs:
            yield sse({"type": "error", "message":
                       "The model did not return usable question/answer "
                       "pairs. Try again, or switch provider."})
            return
        try:
            verbatim = _verbatim_faq_pairs(payload.source)
        except Exception:
            verbatim = []
        if verbatim:
            yield sse({"type": "verbatim", "entries": verbatim})
        yield sse({"type": "done", "entries": pairs[:n],
                   "model": model or "", "verbatim": len(verbatim)})

    from fastapi.responses import StreamingResponse
    return StreamingResponse(events(), media_type="text/event-stream",
                             headers={"Cache-Control": "no-store",
                                      "X-Accel-Buffering": "no"})


@router.post("/admin/faq/bulk")
def admin_faq_bulk(payload: FaqBulkReq,
                   x_admin_password: str | None = Header(default=None)):
    """Save the drafts a person APPROVED, and only those.

    Goes through the same merge as autogenerate, so a curated answer is
    still never overwritten and a question already present is still skipped
    rather than duplicated.
    """
    _require_admin(x_admin_password)
    pairs = [{"question": (e or {}).get("question", ""),
              "answer": (e or {}).get("answer", "")}
             for e in (payload.entries or [])
             if (e or {}).get("question") and (e or {}).get("answer")]
    if not pairs:
        raise HTTPException(status_code=400, detail="Nothing to save")
    merged = faq_store.merge_questions(payload.source or "",
                                       payload.product or payload.category,
                                       pairs, category=payload.category)
    merged["source"] = payload.source
    return merged


@router.post("/admin/faq/import")
async def admin_faq_import(request: Request,
                           file: UploadFile = File(...),
                           x_admin_password: str | None = Header(default=None)):
    """Read question/answer pairs OUT of a document, without indexing it.

    A support team that already has an FAQ -- a Word document, a page of the
    website, a spreadsheet exported to text -- has answers somebody already
    approved. Putting that through the document pipeline is the wrong shape:
    it would be chunked and retrieved from, when what is wanted is the pairs
    themselves, served exactly as written.

    Nothing is saved here either. The pairs come back for the same review the
    drafting flow uses, because an import is exactly as capable of producing
    a mangled pair as a model is.
    """
    _require_admin(x_admin_password)
    raw = await file.read()
    if not raw:
        raise HTTPException(status_code=400, detail="That file is empty")

    import tempfile
    suffix = os.path.splitext(file.filename or "")[1] or ".txt"
    tmp = None
    try:
        with tempfile.NamedTemporaryFile(delete=False, suffix=suffix) as fh:
            fh.write(raw)
            tmp = fh.name
        from parsing import extract_pages
        pages = extract_pages(tmp)
    except Exception as exc:
        logger.warning(f"FAQ import could not read {file.filename!r}: {exc}")
        raise HTTPException(status_code=400,
                            detail=f"Could not read that file: {exc}")
    finally:
        if tmp:
            try:
                os.unlink(tmp)
            except OSError:
                pass

    text = "\n\n".join(t for _pno, t in (pages or []) if t and t.strip())
    if not text.strip():
        raise HTTPException(status_code=422,
                            detail="No text could be read from that file.")

    # Structured first: a document that already marks its questions does not
    # need a model to find them, and a literal read cannot paraphrase.
    pairs = _pairs_from_marked_text(text)
    how = "read from the file"

    if not pairs:
        # Otherwise ask a model to pull out the pairs that ARE there, which
        # is a different instruction from writing new ones: nothing may be
        # composed, and anything without an answer in the file is dropped.
        prompt = (
            "The document below is an existing FAQ or support page.\n\n"
            f"<document>\n{text[:12000]}\n</document>\n\n"
            "Extract the question-and-answer pairs it ALREADY CONTAINS. "
            "Rules:\n"
            "- Copy the wording. Do not rewrite, summarise or improve it.\n"
            "- Do not invent a question, and do not answer one the document "
            "leaves unanswered.\n"
            "- Skip headings, navigation and contact details.\n\n"
            "Return ONLY a JSON array, no other text, in this exact form:\n"
            '[{"question": "...", "answer": "..."}]')
        try:
            from llm import generate_with_fallback
            out = generate_with_fallback("accurate", prompt)
        except Exception as exc:
            raise HTTPException(status_code=502, detail=f"Import failed: {exc}")
        if (out or {}).get("provider") == "none":
            raise HTTPException(
                status_code=502,
                detail="No model could be reached to read that file, and it "
                       "carries no question markers to read literally.")
        pairs = _parse_qa_json((out or {}).get("text", "") or "")
        how = "read by " + str((out or {}).get("model") or "the model")

    if not pairs:
        raise HTTPException(
            status_code=422,
            detail="No question and answer pairs could be found in that file.")
    return {"entries": pairs[:60], "file": file.filename, "how": how,
            "count": len(pairs[:60])}


# "Q: ... A: ..." and "Question: ... Answer: ..." are how exported FAQs
# actually look, and a file that marks its pairs should never need a model:
# reading it literally is both free and incapable of paraphrasing.
_Q_MARK = re.compile(r"^\s*(?:Q|Question)\s*[:.\)-]\s*(.+)$", re.I)


_A_MARK = re.compile(r"^\s*(?:A|Answer)\s*[:.\)-]\s*(.+)$", re.I)


def _pairs_from_marked_text(text: str) -> list[dict]:
    pairs, q, a = [], None, []
    for line in (text or "").split("\n"):
        mq = _Q_MARK.match(line)
        ma = _A_MARK.match(line)
        if mq:
            if q and a:
                pairs.append({"question": q, "answer": " ".join(a).strip()})
            q, a = mq.group(1).strip(), []
        elif ma and q:
            a = [ma.group(1).strip()]
        elif q and a and not line.strip():
            # A blank line ENDS the answer. Without this the pair ran on into
            # whatever followed it -- the last answer in a file swallowed the
            # "Contact us at ..." footer sitting two lines below it.
            pairs.append({"question": q, "answer": " ".join(a).strip()})
            q, a = None, []
        elif q and a and line.strip():
            # A wrapped answer keeps going to the end of its paragraph, which
            # is how these documents lay one out.
            a.append(line.strip())
    if q and a:
        pairs.append({"question": q, "answer": " ".join(a).strip()})
    return [p for p in pairs if p["question"] and p["answer"]]
